=== amtrack/sfdx-browserforce-plugin/src/plugins/salesforce-cpq-config/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/amtrack/sfdx-browserforce-plugin/src/plugins/salesforce-cpq-config/schema.json",
  "title": "SalesforceCpqConfig Settings",
  "type": "object",
  "properties": {
    "documents": {
      "type": "object",
      "title": "Documents",
      "properties": {
        "documentFolder": {
          "type": "string",
          "title": "Document Folder"
        },
        "hideDocumentName": {
          "type": "boolean",
          "title": "Hide Document Name"
        },
        "fullPagePreview": {
          "type": "boolean",
          "title": "Full Page Preview"
        },
        "excludeHiddenLinesInGroupTotals": {
          "type": "boolean",
          "title": "Exclude Hidden Lines In Group Totals"
        },
        "attachmentTarget": {
          "type": "string",
          "title": "Attachment Target"
        },
        "postToFeed": {
          "type": "boolean",
          "title": "Post to Feed?"
        },
        "enableMultiLanguageTranslations": {
          "type": "boolean",
          "title": "Enable Multi-Language Translations"
        }
      }
    },
    "groups": {
      "type": "object",
      "title": "Groups",
      "properties": {
        "solutionGroupsEnabled": {
          "type": "boolean",
          "title": "Solution Groups Enabled"
        },
        "object": {
          "type": "string",
          "title": "Object"
        },
        "nameField": {
          "type": "string",
          "title": "Name Field"
        },
        "descriptionField": {
          "type": "string",
          "title": "Description Field"
        },
        "requireGroupName": {
          "type": "boolean",
          "title": "Require Group Name"
        }
      }
    },
    "lineEditor": {
      "type": "object",
      "title": "Line Editor",
      "properties": {
        "hideRenewedAssetsWhenEditing": {
          "type": "boolean",
          "title": "Hide Renewed Assets When Editing"
        },
        "visualizeProductHierarchy": {
          "type": "boolean",
          "title": "Visualize Product Hierarchy"
        },
        "preserveBundleStructure": {
          "type": "boolean",
          "title": "Preserve Bundle Structure"
        },
        "keepBundleTogether": {
          "type": "boolean",
          "title": "Keep Bundle Together"
        },
        "totalsField": {
          "type": "string",
          "title": "Totals Field"
        },
        "lineSubtotalsTotalField": {
          "type": "string",
          "title": "Line Subtotals Total Field"
        },
        "largeQuoteThreshold": {
          "type": "number",
          "title": "Large Quote Threshold"
        },
        "quoteBatchSize": {
          "type": "number",
          "title": "Quote Batch Size"
        },
        "enableExpandCollapseBundles": {
          "type": "boolean",
          "title": "Enable Expand/Collapse Bundles"
        },
        "defaultBundleSetting": {
          "type": "string",
          "title": "Default Bundle Setting"
        },
        "actionsColumnPlacement": {
          "type": "string",
          "title": "Actions Column Placement"
        },
        "enableMultiLineDelete": {
          "type": "boolean",
          "title": "Enable Multi Line Delete"
        },
        "productConfigurationInitializer": {
          "type": "string",
          "title": "Product Configuration Initializer"
        },
        "enableAssetUpgrades": {
          "type": "boolean",
          "title": "Enable Asset Upgrades"
        },
        "groupSubtotalsField": {
          "type": "string",
          "title": "Group Subtotals Field"
        },
        "wrapButtons": {
          "type": "boolean",
          "title": "Wrap Buttons"
        },
        "validateLargeQuotes": {
          "type": "boolean",
          "title": "Validate Large Quotes"
        },
        "enableCompactMode": {
          "type": "boolean",
          "title": "Enable Compact Mode"
        },
        "enableLargeQuoteExperience": {
          "type": "boolean",
          "title": "Enable Large Quote Experience"
        },
        "enableColumnResizing": {
          "type": "boolean",
          "title": "Enable Column Resizing"
        }
      }
    },
    "plugins": {
      "type": "object",
      "title": "Plugins",
      "properties": {
        "legacyPageSecurityPlugin": {
          "type": "string",
          "title": "Legacy Page Security Plugin"
        },
        "electronicSignaturePlugin": {
          "type": "string",
          "title": "Electronic Signature Plugin"
        },
        "billingPlugin": {
          "type": "string",
          "title": "Billing Plugin"
        },
        "productSearchPlugin": {
          "type": "string",
          "title": "Product Search Plugin"
        },
        "recommendedProductsPlugin": {
          "type": "string",
          "title": "Recommended Products Plugin"
        },
        "legacyQuoteCalculatorPlugin": {
          "type": "string",
          "title": "Legacy Quote Calculator Plugin"
        },
        "documentStorePlugin": {
          "type": "string",
          "title": "Document Store Plugin"
        },
        "quoteCalculatorPlugin": {
          "type": "string",
          "title": "Quote Calculator Plugin"
        },
        "orderManagementPlugin": {
          "type": "string",
          "title": "Order Management Plugin"
        },
        "qleCustomActionPlugin": {
          "type": "string",
          "title": "QLE Custom Action Plugin"
        }
      }
    },
    "pricingAndCalculation": {
      "type": "object",
      "title": "Pricing and Calculation",
      "properties": {
        "currencySymbol": {
          "type": "string",
          "title": "Currency Symbol"
        },
        "useInactivePrices": {
          "type": "boolean",
          "title": "Use Inactive Prices"
        },
        "unitPriceScale": {
          "type": "number",
          "title": "Unit Price Scale"
        },
        "calculateImmediately": {
          "type": "boolean",
          "title": "Calculate Immediately"
        },
        "enableQuickCalculate": {
          "type": "boolean",
          "title": "Enable Quick Calculate"
        },
        "allowNonConsecutiveCustomSegments": {
          "type": "boolean",
          "title": "Allow Non-Consecutive Custom Segments"
        },
        "enablePricingGuidance": {
          "type": "boolean",
          "title": "Enable Pricing Guidance"
        },
        "quoteLineEditsForUsageBasedPricing": {
          "type": "boolean",
          "title": "Quote Line Edits for Usage Based Pricing"
        },
        "useLegacyCalculator": {
          "type": "boolean",
          "title": "Use Legacy Calculator"
        },
        "disableBackgroundCalculationRefresh": {
          "type": "boolean",
          "title": "Disable Background Calculation Refresh"
        },
        "enableUsageBasedPricing": {
          "type": "boolean",
          "title": "Enable Usage Based Pricing"
        },
        "hideUncalculatedQuoteWarning": {
          "type": "boolean",
          "title": "Hide Uncalculated Quote Warning"
        },
        "useIntegrationUserForCalculations": {
          "type": "boolean",
          "title": "Use Integration User for Calculations"
        }
      }
    },
    "subscriptionsAndRenewals": {
      "type": "object",
      "title": "Subscriptions and Renewals",
      "properties": {
        "renewalModel": {
          "type": "string",
          "title": "Renewal Model"
        },
        "disableAddSubscriptions": {
          "type": "boolean",
          "title": "Disable Add Subscriptions"
        },
        "allowRenewalQuotesWithoutAssets": {
          "type": "boolean",
          "title": "Allow Renewal Quotes Without Assets"
        },
        "subscriptionProratePrecision": {
          "type": "string",
          "title": "Subscription Prorate Precision"
        },
        "includeNetNewProductsInMaintenance": {
          "type": "boolean",
          "title": "Include Net-new Products in Maintenance"
        },
        "contractInForeground": {
          "type": "boolean",
          "title": "Contract In Foreground"
        },
        "enableEvergreenSubscriptions": {
          "type": "boolean",
          "title": "Enable Evergreen Subscriptions"
        },
        "legacyAmendRenewService": {
          "type": "boolean",
          "title": "Legacy Amend/Renew Service"
        },
        "amendContractsInBackground": {
          "type": "boolean",
          "title": "Amend Contracts in Background"
        },
        "bypassPreserveBundleStructure": {
          "type": "boolean",
          "title": "Bypass Preserve Bundle Structure"
        },
        "subscriptionTermUnit": {
          "type": "string",
          "title": "Subscription Term Unit"
        },
        "reEvaluateBundleLogicOnRenewals": {
          "type": "boolean",
          "title": "Re-evaluate Bundle Logic on Renewals"
        },
        "poTRenewalsContractingFromOrders": {
          "type": "boolean",
          "title": "PoT Renewals (Contracting from Orders)"
        },
        "disableProductBundleSubTypeChecks": {
          "type": "boolean",
          "title": "Disable Product Bundle Sub Type Checks"
        },
        "useCurrentSubscriptionOnAssets": {
          "type": "boolean",
          "title": "Use Current Subscription on Assets"
        }
      }
    },
    "quote": {
      "type": "object",
      "title": "Quote",
      "properties": {
        "disableInitialQuoteSync": {
          "type": "boolean",
          "title": "Disable Initial Quote Sync"
        },
        "disableQuoteContactDefaulting": {
          "type": "boolean",
          "title": "Disable Quote Contact Defaulting"
        },
        "allowOptionDeletion": {
          "type": "boolean",
          "title": "Allow Option Deletion"
        },
        "disableQuoteAddressDefaulting": {
          "type": "boolean",
          "title": "Disable Quote Address Defaulting"
        },
        "primaryQuoteKeepsOpportunityProducts": {
          "type": "boolean",
          "title": "Primary Quote Keeps Opportunity Products"
        },
        "defaultQuoteValidityDays": {
          "type": "number",
          "title": "Default Quote Validity (Days)"
        }
      }
    },
    "order": {
      "type": "object",
      "title": "Order",
      "properties": {
        "requireApprovedQuote": {
          "type": "boolean",
          "title": "Require Approved Quote"
        },
        "defaultOrderStartDate": {
          "type": "string",
          "title": "Default Order Start Date"
        },
        "allowMultipleOrders": {
          "type": "boolean",
          "title": "Allow Multiple Orders"
        },
        "createOrdersWithoutOpportunities": {
          "type": "boolean",
          "title": "Create Orders Without Opportunities"
        }
      }
    },
    "additionalSettings": {
      "type": "object",
      "title": "Additional Settings",
      "properties": {
        "triggersDisabled": {
          "type": "boolean",
          "title": "Triggers Disabled"
        },
        "quantityScale": {
          "type": "number",
          "title": "Quantity Scale"
        },
        "sortProductsInMemory": {
          "type": "boolean",
          "title": "Sort Products In Memory"
        },
        "multipleBundlesView": {
          "type": "string",
          "title": "Multiple Bundles View"
        },
        "externalConfiguratorUrl": {
          "type": "string",
          "title": "External Configurator URL"
        },
        "thirdPartyConfigurator": {
          "type": "boolean",
          "title": "Third Party Configurator"
        },
        "openSearchFilterByDefault": {
          "type": "boolean",
          "title": "Open Search Filter By Default"
        },
        "hideFeaturesWithHiddenOptions": {
          "type": "boolean",
          "title": "Hide Features with Hidden Options"
        },
        "hideProductSearchBar": {
          "type": "boolean",
          "title": "Hide Product Search Bar"
        },
        "productResultsGroupFieldName": {
          "type": "string",
          "title": "Product Results Group Field Name"
        },
        "productDescriptionField": {
          "type": "string",
          "title": "Product Description Field"
        },
        "theme": {
          "type": "string",
          "title": "Theme"
        },
        "useGlobalHeaderPermission": {
          "type": "boolean",
          "title": "Use Global Header Permission"
        },
        "serviceRegion": {
          "type": "string",
          "title": "Service Region"
        },
        "enableProductOptionDrawer": {
          "type": "boolean",
          "title": "Enable Product Option Drawer"
        },
        "enableLargeConfigurations": {
          "type": "boolean",
          "title": "Enable Large Configurations"
        },
        "nestedBundlesForExternalConfigurator": {
          "type": "boolean",
          "title": "Nested Bundles for External Configurator"
        }
      }
    }
  }
}

=== amtrack/sfdx-browserforce-plugin/src/plugins/salesforce-cpq-config/formConfig.json
{
  "documents": {
    "label": "Documents",
    "component": "tab",
    "id": "page:form:pb:j_id71_lbl",
    "properties": {
      "documentFolder": {
        "label": "Document Folder",
        "component": "select",
        "type": "string",
        "name": "page:form:pb:j_id72:j_id73:j_id75"
      },
      "hideDocumentName": {
        "label": "Hide Document Name",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id72:j_id84"
      },
      "fullPagePreview": {
        "label": "Full Page Preview",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id72:j_id88"
      },
      "excludeHiddenLinesInGroupTotals": {
        "label": "Exclude Hidden Lines In Group Totals",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id72:j_id90"
      },
      "attachmentTarget": {
        "label": "Attachment Target",
        "component": "select",
        "type": "string",
        "name": "page:form:pb:j_id72:j_id78:j_id80"
      },
      "postToFeed": {
        "label": "Post to Feed?",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id72:j_id85:j_id87"
      },
      "enableMultiLanguageTranslations": {
        "label": "Enable Multi-Language Translations",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id72:j_id89"
      }
    }
  },
  "groups": {
    "label": "Groups",
    "component": "tab",
    "id": "page:form:pb:j_id105_lbl",
    "properties": {
      "solutionGroupsEnabled": {
        "label": "Solution Groups Enabled",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:groupSettings:j_id106"
      },
      "object": {
        "label": "Object",
        "component": "input",
        "type": "string",
        "name": "page:form:pb:groupSettings:j_id109:j_id111"
      },
      "nameField": {
        "label": "Name Field",
        "component": "select",
        "type": "string",
        "name": "page:form:pb:groupSettings:j_id114:j_id116"
      },
      "descriptionField": {
        "label": "Description Field",
        "component": "select",
        "type": "string",
        "name": "page:form:pb:groupSettings:j_id120:j_id122"
      },
      "requireGroupName": {
        "label": "Require Group Name",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:groupSettings:j_id108"
      }
    }
  },
  "lineEditor": {
    "label": "Line Editor",
    "component": "tab",
    "id": "page:form:pb:j_id125_lbl",
    "properties": {
      "hideRenewedAssetsWhenEditing": {
        "label": "Hide Renewed Assets When Editing",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id126:j_id127:j_id129"
      },
      "visualizeProductHierarchy": {
        "label": "Visualize Product Hierarchy",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id126:j_id135"
      },
      "preserveBundleStructure": {
        "label": "Preserve Bundle Structure",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id126:j_id137"
      },
      "keepBundleTogether": {
        "label": "Keep Bundle Together",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id126:j_id139"
      },
      "totalsField": {
        "label": "Totals Field",
        "component": "select",
        "type": "string",
        "name": "page:form:pb:j_id126:j_id141:j_id143"
      },
      "lineSubtotalsTotalField": {
        "label": "Line Subtotals Total Field",
        "component": "select",
        "type": "string",
        "name": "page:form:pb:j_id126:j_id153:j_id155"
      },
      "largeQuoteThreshold": {
        "label": "Large Quote Threshold",
        "component": "input",
        "type": "number",
        "name": "page:form:pb:j_id126:j_id160"
      },
      "quoteBatchSize": {
        "label": "Quote Batch Size",
        "component": "input",
        "type": "number",
        "name": "page:form:pb:j_id126:j_id162"
      },
      "enableExpandCollapseBundles": {
        "label": "Enable Expand/Collapse Bundles",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id126:j_id164"
      },
      "defaultBundleSetting": {
        "label": "Default Bundle Setting",
        "component": "select",
        "type": "string",
        "name": "page:form:pb:j_id126:j_id166:j_id168"
      },
      "actionsColumnPlacement": {
        "label": "Actions Column Placement",
        "component": "select",
        "type": "string",
        "name": "page:form:pb:j_id126:j_id130:j_id132"
      },
      "enableMultiLineDelete": {
        "label": "Enable Multi Line Delete",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id126:j_id136"
      },
      "productConfigurationInitializer": {
        "label": "Product Configuration Initializer",
        "component": "input",
        "type": "string",
        "name": "page:form:pb:j_id126:j_id138"
      },
      "enableAssetUpgrades": {
        "label": "Enable Asset Upgrades",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id126:j_id140"
      },
      "groupSubtotalsField": {
        "label": "Group Subtotals Field",
        "component": "select",
        "type": "string",
        "name": "page:form:pb:j_id126:j_id147:j_id149"
      },
      "wrapButtons": {
        "label": "Wrap Buttons",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id126:j_id159"
      },
      "validateLargeQuotes": {
        "label": "Validate Large Quotes",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id126:j_id159"
      },
      "enableCompactMode": {
        "label": "Enable Compact Mode",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id126:j_id163"
      },
      "enableLargeQuoteExperience": {
        "label": "Enable Large Quote Experience",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id126:j_id165"
      },
      "enableColumnResizing": {
        "label": "Enable Column Resizing",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id126:j_id171"
      }
    }
  },
  "plugins": {
    "label": "Plugins",
    "component": "tab",
    "id": "page:form:pb:j_id172_lbl",
    "properties": {
      "legacyPageSecurityPlugin": {
        "label": "Legacy Page Security Plugin",
        "component": "input",
        "type": "string",
        "name": "page:form:pb:j_id173:j_id174"
      },
      "electronicSignaturePlugin": {
        "label": "Electronic Signature Plugin",
        "component": "input",
        "type": "string",
        "name": "page:form:pb:j_id173:j_id175"
      },
      "billingPlugin": {
        "label": "Billing Plugin",
        "component": "input",
        "type": "string",
        "name": "page:form:pb:j_id173:j_id176"
      },
      "productSearchPlugin": {
        "label": "Product Search Plugin",
        "component": "input",
        "type": "string",
        "name": "page:form:pb:j_id173:j_id177"
      },
      "recommendedProductsPlugin": {
        "label": "Recommended Products Plugin",
        "component": "input",
        "type": "string",
        "name": "page:form:pb:j_id173:j_id178"
      },
      "legacyQuoteCalculatorPlugin": {
        "label": "Legacy Quote Calculator Plugin",
        "component": "input",
        "type": "string",
        "name": "page:form:pb:j_id173:j_id178"
      },
      "documentStorePlugin": {
        "label": "Document Store Plugin",
        "component": "input",
        "type": "string",
        "name": "page:form:pb:j_id173:j_id180"
      },
      "quoteCalculatorPlugin": {
        "label": "Quote Calculator Plugin",
        "component": "input",
        "type": "string",
        "name": "page:form:pb:j_id173:j_id181"
      },
      "orderManagementPlugin": {
        "label": "Order Management Plugin",
        "component": "input",
        "type": "string",
        "name": "page:form:pb:j_id173:j_id182"
      },
      "qleCustomActionPlugin": {
        "label": "QLE Custom Action Plugin",
        "component": "input",
        "type": "string",
        "name": "page:form:pb:j_id173:j_id183"
      }
    }
  },
  "pricingAndCalculation": {
    "label": "Pricing and Calculation",
    "component": "tab",
    "id": "page:form:pb:j_id184_lbl",
    "properties": {
      "currencySymbol": {
        "label": "Currency Symbol",
        "component": "input",
        "type": "string",
        "name": "page:form:pb:j_id185:j_id186"
      },
      "unitPriceScale": {
        "label": "Unit Price Scale",
        "component": "input",
        "type": "number",
        "name": "page:form:pb:j_id185:j_id188"
      },
      "enableQuickCalculate": {
        "label": "Enable Quick Calculate",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id185:j_id190"
      },
      "allowNonConsecutiveCustomSegments": {
        "label": "Allow Non-Consecutive Custom Segments",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id185:j_id192"
      },
      "enablePricingGuidance": {
        "label": "Enable Pricing Guidance",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id185:j_id194"
      },
      "quoteLineEditsForUsageBasedPricing": {
        "label": "Quote Line Edits for Usage Based Pricing",
        "component": "input",
        "type": "boolean",
        "name": "page:form:pb:j_id185:j_id196"
      },
      "useLegacyCalculator": {
        "label": "Use Legacy Calculator",
        "component": "input",
        "type": "boolean",
